# permissions for end users to view debugtasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: debugtask-viewer-role
rules:
- apiGroups:
  - debug.mahuang.cn
  resources:
  - debugtasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - debug.mahuang.cn
  resources:
  - debugtasks/status
  verbs:
  - get
