// +build !ignore_autogenerated

/*
Copyright 2020 mahuang.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DebugObjectInfo) DeepCopyInto(out *DebugObjectInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DebugObjectInfo.
func (in *DebugObjectInfo) DeepCopy() *DebugObjectInfo {
	if in == nil {
		return nil
	}
	out := new(DebugObjectInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DebugTask) DeepCopyInto(out *DebugTask) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DebugTask.
func (in *DebugTask) DeepCopy() *DebugTask {
	if in == nil {
		return nil
	}
	out := new(DebugTask)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DebugTask) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DebugTaskList) DeepCopyInto(out *DebugTaskList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DebugTask, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DebugTaskList.
func (in *DebugTaskList) DeepCopy() *DebugTaskList {
	if in == nil {
		return nil
	}
	out := new(DebugTaskList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DebugTaskList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DebugTaskSpec) DeepCopyInto(out *DebugTaskSpec) {
	*out = *in
	if in.DebugObjectInfo != nil {
		in, out := &in.DebugObjectInfo, &out.DebugObjectInfo
		*out = new(DebugObjectInfo)
		**out = **in
	}
	if in.TargetObjectInfo != nil {
		in, out := &in.TargetObjectInfo, &out.TargetObjectInfo
		*out = new(TargetObjectInfo)
		**out = **in
	}
	if in.StartTime != nil {
		in, out := &in.StartTime, &out.StartTime
		*out = (*in).DeepCopy()
	}
	if in.EndTime != nil {
		in, out := &in.EndTime, &out.EndTime
		*out = (*in).DeepCopy()
	}
	if in.History != nil {
		in, out := &in.History, &out.History
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DebugTaskSpec.
func (in *DebugTaskSpec) DeepCopy() *DebugTaskSpec {
	if in == nil {
		return nil
	}
	out := new(DebugTaskSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DebugTaskStatus) DeepCopyInto(out *DebugTaskStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DebugTaskStatus.
func (in *DebugTaskStatus) DeepCopy() *DebugTaskStatus {
	if in == nil {
		return nil
	}
	out := new(DebugTaskStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetObjectInfo) DeepCopyInto(out *TargetObjectInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetObjectInfo.
func (in *TargetObjectInfo) DeepCopy() *TargetObjectInfo {
	if in == nil {
		return nil
	}
	out := new(TargetObjectInfo)
	in.DeepCopyInto(out)
	return out
}
